default[:sch_mybatis][:source] = "mybatis-3.0.6-migrations.zip"
default[:sch_mybatis][:version] = "3.0.6"
default[:sch_mybatis][:install_folder] = "/usr/local/mybatis"
default[:sch_mybatis][:installed_name] = "mybatis_exe"
default[:sch_mybatis][:migrations_working_folder] = "/usr/local/mybatis/migrations/testdb"
default[:sch_mybatis][:create_mybatis_changelog_table] = true # if true, changelog table is only created on initial mybatis migration
default[:sch_mybatis][:environment] = "development"
default[:sch_mybatis][:db_name] = "litrpo" # the database to run migrations against
default[:sch_mybatis][:db_driver] = "com.mysql.jdbc.Driver"
default[:sch_mybatis][:db_url] = "jdbc:mysql://lp-qa-test-dbapr13.ckflanb1yqzx.us-east-1.rds.amazonaws.com"
default[:sch_mybatis][:db_port] = "3306" # if this is blank mybatis will use the node[:samconnect][:iondb.....] values
default[:sch_mybatis][:db_username] = "" # if db_port (above) is blank mybatis will use the node[:samconnect][:iondb.....] values
default[:sch_mybatis][:db_password] = "" # if db_port (above) is blank mybatis will use the node[:samconnect][:iondb.....] values
default[:sch_mybatis][:run_bootstrap] = false # change to true if you want mybatis to run a bootstrap at first use
default[:sch_mybatis][:bootstrap_file_in_git] = false
default[:sch_mybatis][:bootstrap_script_location] = "" # For example "http://somerepo.com/repositories/releases/0.1.9b"
default[:sch_mybatis][:bootstrap_script_name] = "bootstrap.sql" # for example "ion.db.populate-0.1.9b.zip"
default[:sch_mybatis][:bootstrap_script_username] = "" #this is only used if not configured for git
default[:sch_mybatis][:bootstrap_script_password] = "" #again only used if not conifgured for git
default[:sch_mybatis][:migrate_command] = "version" 
default[:sch_mybatis][:migrate_to_version] = "" # override this to the version nuber 'XXXXX' to upgrade (or downgrade) to a specific config
default[:sch_mybatis][:migration_scripts] = Array.new # array of URL's
default[:sch_mybatis][:use_git_repo] = true
default[:sch_mybatis][:git_security_type] = "oauth" # must be either "oauth" or "deploy_key"
default[:sch_mybatis][:git_repo_destination] = "/usr/local/mybatis/git_space"
default[:sch_mybatis][:git_repo] = "" # for examlpe git@github.com:fred/fred.git"
default[:sch_mybatis][:git_scripts_dir] = "/usr/local/mybatis/git_space/current/dbscripts/myBatis"
default[:sch_mybatis][:deploy_key] = "" # must use \n instead of CRLF and have standard begining and ending ---- delimiters ----
default[:sch_mybatis][:deploy_revision] = "master"
default[:sch_mybatis][:script_timeout] = 10800
default[:mybatis][:installer_url] = "https://github.com/ltolapi/mybatis_repo/blob/master/#{node[:sch_mybatis][:source]}?raw=true"
default[:mybatis][:mysql_connector_java_version] = "5.1.21"